version: '2'
services:
    keycloak-server:
        container_name: keycloak-server
        image: openfact/keycloak-postgres
        external_links:
            - keycloak-postgresql:postgres
        environment:
            - POSTGRES_DATABASE=keycloak
            - POSTGRES_USER=keycloak
            - POSTGRES_PASSWORD=password
            #jboss is using legacy linking environment variables
            - POSTGRES_PORT_5432_TCP_ADDR=postgres
            - POSTGRES_PORT_5432_TCP_PORT=5432
        ports:
            - 10090:8080
        volumes:
            - ./keycloak-server/conf/standalone.xml:/opt/jboss/keycloak/standalone/configuration/standalone.xml
            - ./keycloak-server/user/keycloak-add-user.json:/opt/jboss/keycloak/standalone/configuration/keycloak-add-user.json
            - ./keycloak-server/cli-scripts:/cli-scripts
            - ./keycloak-server/drop-ins:/drop-ins
        restart: unless-stopped
    keycloak-postgresql:
        extends:
          file: keycloak-postgres.yml
          service: keycloak-postgresql
